[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-executor = { features = [
    "nightly",
    "arch-cortex-m",
    "executor-thread",
    "integrated-timers",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-rp = { features = [
    "unstable-traits",
    "nightly",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    "intrinsics",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-time = { features = [
    "nightly",
    "unstable-traits",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-sync = { features = [
    "nightly",
], git = "https:///github.com/embassy-rs/embassy" }

cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
portable-atomic = { version = "1.5", features = ["critical-section"] }
rtt-target = "0.4.0"
static_cell = "2"

[profile.dev]
opt-level = 1
lto = "thin"

[profile.release]
opt-level = "z"
lto = "fat"
