[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{{crate_name}}"

[lib]

[dependencies]
embassy-embedded-hal = { version = "0.1.0", git = "https:///github.com/embassy-rs/embassy" }
embassy-executor = { version = "0.2.0", features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "integrated-timers",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-futures = { version = "0.1.0", git = "https:///github.com/embassy-rs/embassy" }
embassy-net = { version = "0.1.0", features = [
    "nightly",
    "tcp",
    "dhcpv4",
    "medium-ethernet",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-sync = { version = "0.2.0", git = "https:///github.com/embassy-rs/embassy" }
embassy-rp = { version = "0.1.0", features = [
    "unstable-traits",
    "nightly",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    "rom-func-cache",
    "intrinsics",
    "rom-v2-intrinsics",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-time = { version = "0.1.0", features = [
    "nightly",
    "unstable-traits",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-usb = { version = "0.1.0", git = "https:///github.com/embassy-rs/embassy" }
embassy-usb-logger = { version = "0.1.0", git = "https:///github.com/embassy-rs/embassy" }

panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
rtt-target = "0.4.0"

cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"

[profile.dev]
debug = true
debug-assertions = true
opt-level = "z"
lto = "thin"

[profile.dev.build-override]
debug = true
debug-assertions = true

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "fat"
