[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
# embassy-embedded-hal = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy.git" }
embassy-sync = { version = "0.5.0", git = "https://github.com/embassy-rs/embassy.git" }
embassy-executor = { version = "0.4.0", git = "https://github.com/embassy-rs/embassy.git", features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "integrated-timers",
] }
embassy-time = { version = "0.2", git = "https://github.com/embassy-rs/embassy.git" }
embassy-rp = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy.git", features = [
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    "rom-func-cache",
    "intrinsics",
    "rom-v2-intrinsics",
] }
# embassy-usb = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy.git" }
# embassy-net = { version = "0.2.0", git = "https://github.com/embassy-rs/embassy.git", features = [
#     "tcp",
#     "udp",
#     "dhcpv4",
#     "medium-ethernet",
# ] }
# embassy-net-wiznet = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy.git" }
# embassy-futures = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy.git" }
# embassy-usb-logger = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy.git" }
# cyw43 = { git = "https://github.com/embassy-rs/embassy.git", features = [
#     "firmware-logs",
# ] }
# cyw43-pio = { git = "https://github.com/embassy-rs/embassy.git", features = [
#     "overclock",
# ] }

# fixed = "1.24.0"
# fixed-macro = "1.2.0"

# cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "0.7.3"
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
rtt-target = "0.4.0"
# futures = { version = "0.3.30", default-features = false, features = [
#     "async-await",
#     "cfg-target-has-atomic",
#     "unstable",
# ] }
# display-interface-spi = "0.4.1"
# embedded-graphics = "0.8.1"
# st7789 = "0.7.0"
# display-interface = "0.4.1"
# byte-slice-cast = { version = "1.2.2", default-features = false }
# smart-leds = "0.3.0"
# heapless = "0.8"
# usbd-hid = "0.7.0"

# embedded-hal-1 = { package = "embedded-hal", version = "=1.0.0-rc.3" }
# embedded-hal-async = "1.0.0-rc.3"
# embedded-hal-bus = { version = "0.1.0-rc.3", features = ["async"] }
# embedded-io-async = { version = "0.6.1", features = [] }
# embedded-storage = { version = "0.3" }
static_cell = { version = "2", features = ["nightly"] }
portable-atomic = { version = "1.6.0", features = ["critical-section"] }
# log = "0.4.20"
# pio-proc = "0.2.2"
# pio = "0.2.1"
# rand = { version = "0.8.5", default-features = false }

[profile.dev]
opt-level = 1
lto = "thin"

[profile.release]
opt-level = "z"
lto = "fat"
