[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{{project-name}}"

[lib]

[dependencies]
embassy-executor = { version = "0.3.0", features = [
    "nightly",
    "arch-cortex-m",
    "executor-thread",
    "integrated-timers",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-rp = { version = "0.1.0", features = [
    "unstable-traits",
    "nightly",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    "intrinsics",
], git = "https:///github.com/embassy-rs/embassy" }
embassy-time = { version = "0.1.4", features = [
    "nightly",
    "unstable-traits",
], git = "https:///github.com/embassy-rs/embassy" }

cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
rtt-target = "0.4.0"
static_cell = "2"
portable-atomic = { version = "1.5", features = ["critical-section"] }

[profile.dev]
opt-level = 1
lto = "thin"

[profile.release]
opt-level = "z"
lto = "fat"
