[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip rp2040 --protocol swd"

rustflags = ["-C", "inline-threshold=5", "-C", "no-vectorize-loops"]

[build]
target = "thumbv6m-none-eabi"
